cdc_fuse_fs/main.cc, common/BUILD, common/path.cc, common/path.h, common/path_test.cc, data_store/disk_data_store.cc, manifest/manifest_iterator.cc
Fixes a couple of issues with the FUSE:
- Creates the mount directory if it does not exist. This assumes the mount dir to be the last arg. Ideally, we'd parse the command line and then create the directory, but unfortunately fuse_parse_cmdline already verifies that the dir exists.
- Expands the cache_dir (e.g. ~).
- Fixes a compile issue in manifest_iterator.
=> [cdc_fuse_fs] Fix various issues

asset_stream_manager/multi_session.cc, asset_stream_manager/session.cc, cdc_stream/main.cc, common/port_manager.h, common/port_manager_test.cc, common/port_manager_win.cc
So far, errors from the remote netstat process would only be logged in the asset stream service, for instance when SSH auth failed. However, the errors were not shown to the client, and that's the most important thing.
Also adds some feedback to cdc_stream in case of success.
=> [cdc_stream] Append errors from netstart to status

asset_stream_manager/BUILD, asset_stream_manager/main.cc, cdc_fuse_fs/cdc_fuse_fs.cc, cdc_rsync/BUILD, common/sdk_util.cc, common/sdk_util.h, common/sdk_util_test.cc
--log_dir - directory for log files
--config-dir - directory for the configuration file assets_stream_manager.json
In addition, remove unused functions from SdkUtils and fix build issue with cdc_fuse_fs
=> Add new flags to asset stream manager

.github/workflows/create_release.yml
Modifies the create_release workflow in 2 ways:
- It only runs now if something is pushed to main.
- It creates a tagged release if a tag is pushed.
To create a tagged release, run e.g.
git tag -a v0.1.0 -m "Release 0.1.0" git push origin v0.1.0
=> Improve create_release workflow

cdc_rsync/file_finder_and_sender.cc, cdc_rsync_server/cdc_rsync_server.cc, common/file_watcher_win.cc, common/remote_util.cc, manifest/manifest_updater_test.cc
Running commands like `cdc_rsync C:\assets\* host:~/assets -vr` would create a directory called `~assets`. This CL expands path variables properly.
=> Expand path variables for sync destination

common/file_watcher_win_test.cc
The test
FileWatcherTest/FileWatcherParameterizedTest.RecreateWatchedDir/ReadDirectoryChangesExW
is flaky. This CL doesn't fix the root cause, but it fixes the indefinite spin in GetChangedFiles when there is no file change.
=> Fix possible indefinite loop in FileWatcherTest

common/process_test.cc
The issue was consistently reproducible by adding a sleep right after starting the process.
Use ping instead of timeout now, because ping doesn't read user input.
=> "Proper" fix for "Input redirection is not supported" issue with timeout

WORKSPACE, all_files.vcxitems, asset_stream_manager/BUILD, asset_stream_manager/asset_stream_config.cc, asset_stream_manager/asset_stream_config.h, asset_stream_manager/base_command.cc, asset_stream_manager/base_command.h, asset_stream_manager/main.cc, asset_stream_manager/start_service_command.cc, asset_stream_manager/start_service_command.h, third_party/lyra/BUILD.bazel
Lyra has a nice simple interface, but a few quirks that we work around, mainly in the BaseCommand class:
- It does not support return values from running a command.
- It does not support return values from a custom arg parser.
- Lyra interprets --bad_arg as positional argument.
Fixes #15
=> [cdc_stream] Switch asset_stream_manager to use Lyra

common/file_watcher_win_test.cc
There is a race condition in RecreateWatchedDir where there was a
brief period between the second dir change event and when the file
watcher was actually watching again. If the file was written during
that bried period, it would be missed. The issue could be reproduced
easily by adding a sleep here:
// The watched directory exists and its handle is valid.
if (!first_run) {
++dir_recreate_count_;
if (dir_recreated_cb_) dir_recreated_cb_();
Util::Sleep(1);
}
This CL waits until the watcher is watching again.
=> [common] Fix FileWatcherTest

README.md, cdc_stream/BUILD, cdc_stream/asset_stream_config.cc, cdc_stream/asset_stream_config.h, cdc_stream/background_service_client.cc, cdc_stream/background_service_client.h, cdc_stream/background_service_impl.cc, cdc_stream/background_service_impl.h, cdc_stream/local_assets_stream_manager_client.cc, cdc_stream/local_assets_stream_manager_client.h, cdc_stream/local_assets_stream_manager_service_impl.cc, cdc_stream/session_management_server.h, cdc_stream/start_command.cc, cdc_stream/start_command.h, cdc_stream/start_service_command.cc, cdc_stream/stop_command.cc, common/port_manager_win.cc, common/process.h, common/process_win.cc, common/remote_util.cc, proto/background_service.proto
Starts the streaming service if it's not up and running. This required
adding the ability to run a detached process. By default, all child
processes are killed when the parent process exits. Since detached
child processes don't run with a console, they need to create sub-
processes with CREATE_NO_WINDOW since otherwise a new console pops up,
e.g. for every ssh command.
Polls for 20 seconds while the service starts up. For this purpose,
a BackgroundServiceClient is added. This will be reused in a future CL
by a new stop-service command to exit the service.
Also adds --service-port as additional argument to start-service.
Fixes #14
=> [cdc_stream] Automatically start service

all_files.vcxitems, cdc_stream/BUILD, cdc_stream/background_service_impl.cc, cdc_stream/background_service_impl.h, cdc_stream/main.cc, cdc_stream/start_service_command.cc, cdc_stream/stop_service_command.cc, cdc_stream/stop_service_command.h
Implements cdc_stream stop-service. Also fixes an issue in the
BackgroundService implementation where Exit() would deadlock since
server shutdown waits for all RPCs to exit.
=> [cdc_stream] Implement stop-service command

common/remote_util.cc
This prevents adding args to the commands, e.g.
set CDC_SCP_COMMAND=C:\path\to\scp.exe -i id_rsa.
=> Do not quote ssh/scp commands

cdc_stream/cdc_fuse_manager.cc, cdc_stream/main.cc, cdc_stream/multi_session.cc, cdc_stream/multi_session.h, cdc_stream/multi_session_test.cc, cdc_stream/start_service_command.cc, data_store/data_provider.cc
Fixes a couple of issues found by integration testing:
- Unicode command line args in cdc_stream show up as question marks.
- Log is still named assets_stream_manager instead of cdc_stream.
- An error message contains stadia_assets_stream_manager_v3.exe.
- mount_dir was not the last arg as required by FUSE
- Promoted cache cleanup logs to INFO level since they're important for the proper workings of the system.
- Asset streaming cache dir is still %APPDATA%\GGP\asset_streaming.
=> [cdc_stream] Fix issues found in tests

README.md, cdc_rsync/cdc_rsync_client.cc, cdc_rsync/cdc_rsync_client.h, cdc_rsync/main.cc, cdc_rsync/params.cc, cdc_rsync/params_test.cc, cdc_stream/asset_stream_config.cc, cdc_stream/local_assets_stream_manager_client.cc, cdc_stream/local_assets_stream_manager_client.h, cdc_stream/local_assets_stream_manager_service_impl.cc, cdc_stream/local_assets_stream_manager_service_impl.h, cdc_stream/session.cc, cdc_stream/session.h, cdc_stream/start_command.cc, cdc_stream/start_command.h, cdc_stream/start_service_command.cc, common/port_manager_test.cc, common/remote_util.cc, common/remote_util.h, common/remote_util_test.cc, proto/local_assets_stream_manager.proto
This CL removes the port arguments for both tools.
The port argument can also be specified via the ssh-command and scp-command flags. In fact, if a port is specified by both port flags and ssh/scp commands, they interfere with each other. For ssh, the one specified in ssh-command wins. For scp, the one specified in scp-command wins. To fix this, one would have to parse scp-command and remove the port arg there. Or we could just remove the ssh-port arg. This is what this CL does. Note that if you need a custom port, it's very likely that you also have to define custom ssh and scp commands.
=> [cdc_rsync] [cdc_stream] Remove SSH port argument

all_files.vcxitems, cdc_rsync/BUILD, cdc_rsync/cdc_rsync_client.cc, cdc_rsync/cdc_rsync_client.h, cdc_rsync/params.cc, cdc_rsync/params_test.cc, cdc_stream/BUILD, cdc_stream/asset_stream_config.cc, cdc_stream/asset_stream_config.h, cdc_stream/base_command.cc, cdc_stream/base_command.h, cdc_stream/cdc_stream.vcxproj, cdc_stream/multi_session.cc, cdc_stream/multi_session.h, cdc_stream/session.cc, cdc_stream/session_config.h, cdc_stream/start_command.cc, common/BUILD, common/port_manager.h, common/port_manager_test.cc, common/port_manager_win.cc, common/port_range_parser.cc, common/port_range_parser.h, common/port_range_parser_test.cc, tests_common/BUILD
[cdc_stream] [cdc_rsync] Add --forward-port flag
Adds a flag to set the SSH forwarding port or port range used for
'cdc_stream start-service' and 'cdc_rsync'.
If a single number is passed, e.g. --forward-port 12345, then this
port is used without checking availability of local and remote ports.
If the port is taken, this results in an error when trying to connect.
Note that this restricts the number of connections that stream can
make to one.
If a range is passed, e.g. --forward-port 45000-46000, the tools
search for available ports locally and remotely in that range. This is
more robust, but a bit slower due to the extra overhead.
Optimizes port_manager_win as it was very slow for a large port range.
It's still not optimal, but the time needed to scan 30k ports is
<< 1 seconds now.
=> [cdc_stream] [cdc_rsync] Add --forward-port flag

all_files.vcxitems, cdc_rsync/base/BUILD, cdc_rsync/base/socket.cc, cdc_rsync/base/socket.h, cdc_rsync/cdc_rsync_client.cc, cdc_rsync/cdc_rsync_client.h, cdc_rsync/client_socket.cc, cdc_rsync/client_socket.h, cdc_rsync_server/BUILD, cdc_rsync_server/cdc_rsync_server.cc, cdc_rsync_server/cdc_rsync_server.h, cdc_rsync_server/server_socket.cc, cdc_rsync_server/server_socket.h
Makes ServerSocket multi-platform, mainly by working around some small API differences. The code is largely the same, there should be no differences on Linux.
Also moves WSAStartup() and WSACleanup() up to the Socket level as static methods because it's used by both ClientSocket and ServerSocket, and because it doesn't make sense to do that in the socket class as that would prevent one from using several sockets.
=> [cdc_rsync] Add support for ServerSocket on Windows

common/file_watcher_win.cc, common/file_watcher_win.h, common/file_watcher_win_test.cc
But...
ONCE AND FOR ALL!
A recent change introduced WaitForWatching(), which was supposed to block until the file watcher is actively monitoring the directory. However this always returned immediately since the watcher is in kFailed state if the directory was deleted, which counts as watching (IsWatching returns true for both kRunning and kFailed states).
This CL adds an IsRunning() helper function that returns true only for the kRunning state, which means that the directory is actively being watched.
=> [common] Fix FileWatcherTest once and for all

README.md, cdc_rsync/base/fake_socket.cc, cdc_rsync/cdc_rsync_client.cc, cdc_rsync/zstd_stream.cc, cdc_rsync/zstd_stream.h, cdc_rsync/zstd_stream_test.cc, cdc_rsync_server/unzstd_stream.cc, common/file_watcher_win.cc, common/file_watcher_win.h, common/file_watcher_win_test.cc
Fixes an issue in UnzstdStream where the Read() method always tries to read new input data if no input data is available, instead of first trying to uncompress. Since zstd maintains internal buffers, uncompression might succeed even without reading more input, so this is faster. This bug can lead to pipeline stalls in cdc_rsync.
=> [cdc_rsync] Fix issue in UnzstdStream

common/process.h, common/process_test.cc, common/process_win.cc
This will be needed later for switching to sftp, since calling lcd in sftp is tricky to get right (e.g. may or may not require /cygwin/c on Windows, depending on whether sftp is native or not).
=> [common] Add a way to set the process startup directory

common/remote_util.cc, common/remote_util.h, common/remote_util_test.cc
In a future CL, we will switch from scp to sftp. This CL adds support for calling sftp from RemoteUtil.
In order to maintain backwards compatibility where people still set --scp-command or CDC_SCP_COMMAND instead of the sftp versions, this CL also adds the helper method RemoteUtil::ScpToSftpCommand, which attempts to convert an scp command to an sftp command. This is usually possible since the args are almost the same. For instance, if the scp command is
C:\path\to\scp.exe -P 1234 -i <key_file> -oUserKnownHostsFile=known_hosts
then the corresponding sftp command is most likely
C:\path\to\sftp.exe -P 1234 -i <key_file> -oUserKnownHostsFile=known_hosts
This works for instance for OpenSSH.
=> [RemoteUtil] Add support for sftp

all_files.vcxitems, cdc_rsync/BUILD, cdc_rsync/cdc_rsync.vcxproj, cdc_rsync/cdc_rsync_client.cc, cdc_rsync/cdc_rsync_client.h, cdc_rsync/server_arch.cc, cdc_rsync/server_arch.h, cdc_rsync/server_arch_test.cc, cdc_rsync_server/cdc_rsync_server.cc, integration_tests/cdc_rsync/connection_test.py, integration_tests/cdc_rsync/deployment_test.py, integration_tests/cdc_rsync/upload_test.py, integration_tests/cdc_stream/consistency_test.py, integration_tests/cdc_stream/directory_test.py, integration_tests/cdc_stream/general_test.py, integration_tests/cdc_stream/test_base.py
Adds a ServerArch class whose job it is to encapsulate differences between Windows and Linux cdc_rsync_servers. It detects the type based on a heuristic in the destination path. This is not fool proof and will probably require further work, like falling back to the other type if the detected one doesn't work.
Uses the ServerArch class to determine the different commands to start the server and to deploy the server.
Note that the functionality is not well tested on Windows yet, but copying plain files works.
=> [cdc_rsync] Add initial support for Windows

README.md, cdc_rsync/cdc_rsync_client.cc, cdc_rsync/cdc_rsync_client.h, cdc_rsync/params.cc, cdc_rsync/params_test.cc, cdc_rsync/server_arch.cc, cdc_rsync/server_arch.h, cdc_rsync/server_arch_test.cc, cdc_stream/asset_stream_config.cc, cdc_stream/cdc_fuse_manager.cc, cdc_stream/local_assets_stream_manager_client.cc, cdc_stream/local_assets_stream_manager_client.h, cdc_stream/local_assets_stream_manager_service_impl.cc, cdc_stream/session.cc, cdc_stream/session.h, cdc_stream/start_command.cc, cdc_stream/start_command.h, cdc_stream/start_service_command.cc, proto/local_assets_stream_manager.proto
Use sftp for deploying remote components instead of scp. sftp has the advantage that it can also create directries, chmod files etc., so that we can do everything in one call of sftp instead of mixing scp and ssh calls.
The downside of sftp is that it can't switch to ~ resp. %userprofile% for the remote side, and we have to assume that sftp starts in the user's home dir. This is the default and works on my machines!
cdc_rsync and cdc_stream check the CDC_SFTP_COMMAND env var now and accept --sftp-command flags. If they are not set, the corresponding scp flag and env var is still used, with scp replaced by sftp. This is most likely correct as sftp and scp usually reside in the same directory and share largely identical parameters.
=> [cdc_rsync] [cdc_stream] Switch from scp to sftp

fastcdc/fastcdc.h, fastcdc/fastcdc_test.cc
This ensures that the last byte included in the gear-hash that identified the  chunk boundary is included in the chunk. This ensures chunks are still matched  when the byte immediately after them is changed.
It also initializes the gear hash to all 1's to avoid zero-length chunks when `min_size=0`. It changes the fastcdc `MaxChunkSize` test to use `min_size=0` to test this corner-case.
=> Fix #76 fastcdc chunk boundary off-by-one.

README.md, cdc_rsync/cdc_rsync_client.cc, cdc_rsync/cdc_rsync_client.h, cdc_rsync/params.cc, cdc_rsync/params_test.cc, cdc_rsync/server_arch.cc, cdc_rsync/server_arch.h, common/path.cc, common/path_test.cc, common/port_manager.h, common/port_manager_win.cc, fastcdc/fastcdc.h
Adds support for local syncs of files and folders on the same Windows machine, e.g. cdc_rsync C:\source C:\dest. The main changes are
- Skip the check whether the port is available remotely with PortManager.
- Do not deploy cdc_rsync_server.
- Run cdc_rsync_server directly, not through an SSH tunnel.
The current implementation is not optimal as it starts cdc_rsync_server as a separate process and communicates to it via a TCP port.
=> [cdc_rsync] Enable local syncing

all_files.vcxitems, common/BUILD, common/ansi_filter.cc, common/ansi_filter.h, common/ansi_filter_test.cc, tests_common/BUILD
Adds a function to filter ANSI escape sequences from a string. Executing SSH commands on Windows yields output that is full of ANSI escape sequences if the "-tt" (forced TTY) argument is used. One particular escape sequence sets the window title to "c:\windows\system32\cmd.exe". This string is null terminated and messes with parsing the actual output later in that string. The filter function removes those escape sequences.
The outout is still a bit messed up, even after removing escape sequences. Some sequences delete rows and move the cursor. Without properly interpreting these sequences it doesn't seem possible to retrieve the proper output.
In a future CL the -tt argument is removed on Windows, which removes the necessity to filter ANSI codes. However, sometimes the target architecture …
=> [common] Add ansi_filter

cdc_rsync/cdc_rsync_client.cc, cdc_rsync_server/cdc_rsync_server.cc, common/BUILD, common/log.cc, common/log.h, common/threadpool.cc, common/threadpool.h, common/threadpool_test.cc, integration_tests/cdc_rsync/output_test.py
On Windows, fclose() seems to be very expensive for large files, where closing a 1 GB file takes up to 5 seconds. This CL calls fclose() in background threads. This tremendously improves local syncs, e.g. copying a 4.5 GB, 300 files data set takes only 7 seconds instead of 30 seconds.
Also increases the buffer size for copying from 16K to 128K (better throughput for local copies), and adds a timestamp to debug and verbose console logs (useful when comparing client and server logs).
=> [cdc_rsync] Improve throughput for local copies

all_files.vcxitems, cdc_rsync/BUILD, cdc_rsync/params.cc, cdc_rsync_server/BUILD, cdc_rsync_server/main.cc, common/BUILD, common/build_version.h, common/gamelet_component.cc, common/gamelet_component.h, common/gamelet_component_test.cc
Build id is an optional unique identifier specified during cdc_rsync build via CDC_BUILD_VERSION definition.
If build ids specified on both client and server components it will be used to check the version of server component instead of file size + modified time.
=> [cdc_rsync] [cdc_rsync_server] Add build ID

all_files.vcxitems, cdc_rsync/BUILD, cdc_rsync/cdc_rsync_client.cc, cdc_rsync/cdc_rsync_client.h, cdc_rsync/server_arch.cc, cdc_rsync/server_arch.h, cdc_rsync/server_arch_test.cc, cdc_stream/multi_session.cc, cdc_stream/session.cc, common/BUILD, common/arch_type.cc, common/arch_type.h, common/arch_type_test.cc, common/port_manager.h, common/port_manager_test.cc, common/port_manager_win.cc, common/remote_util.cc, common/remote_util.h, tests_common/BUILD
Improves ServerArch so that it can detect the remote architecture by running uname and checking %PROCESSOR_ARCHITECTURE%. So far, only x64 Linux and x64 Windows are supported, but in the future it is easy to add support for others, e.g. aarch64, as well.
Before the detection is run, the remote architecture is guessed first based on the destination. For instance, if the destination directory starts with "C:\", it pretty much means Windows. If cdc_rsync_server exists and runs fine, there's no need for detection.
Since also PortManager depends on the remote architecture, it has to be adjusted as well. So far, PortManager assumeed that "local" means Windows and "remote" means Linux. This is no longer the case for syncing to Windows devices, so this CL adds the necessary abstractions to …
=> [cdc_rsync] Detect remote architecture

cdc_rsync/cdc_rsync_client.cc, cdc_rsync/main.cc, cdc_rsync/zstd_stream.cc, common/port_manager_test.cc, common/port_manager_win.cc
ss is a modern alternative to netstat. The flags we use and the way we parse the output are compatible with netstat. Since netstat is no longer installed on some Linux distributions, prefer ss, but fall back to netstat if "which ss" fails.
Also tweaks some logging.
=> [PortManager] Prefer ss over netstat on Linux

cdc_rsync/BUILD, cdc_rsync/cdc_rsync_client.cc, cdc_rsync/server_arch.cc, cdc_stream/cdc_fuse_manager.cc, common/port_manager_win.cc, common/remote_util.cc, common/remote_util.h, common/remote_util_test.cc
Adds an ArchType argument to many RemoteUtil methods, which is used to replace -tt (forced pseudo-TTY allocation) by -T (no pseudo-TTY allocation). The -tt option adds tons of ANSI escape sequences to the output and makes it unparsable, even after removing the sequences, as some sequences like "delete the last X characters" are not honoured.
=> [RemoteUtil] Fix output from Windows SSH commands

cdc_indexer/README.md, cdc_indexer/indexer.cc, cdc_indexer/indexer.h, cdc_indexer/main.cc, cdc_stream/multi_session_test.cc, fastcdc/fastcdc.h, fastcdc/fastcdc_test.cc, manifest/manifest_test_base.cc, manifest/manifest_updater.h, manifest/manifest_updater_test.cc
This changes the chunking algorithm from "normalized chunking" to simple "exponential chunking", changes the hash criteria from `hash&mask` to `hash<=threshold`, and changes the gear rollsum to use a multiply instead of a
table lookup.
These are all ideas taken from testing and analysis done at;
* https://github.com/dbaarda/rollsum-chunking/blob/master/RESULTS.rst
* https://github.com/dbaarda/rollsum-tests/blob/master/RESULTS.rst
=> Change fastcdc to a better and simpler algorithm.

cdc_rsync_server/BUILD, cdc_rsync_server/cdc_rsync_server.cc, cdc_rsync_server/server_socket.cc, cdc_rsync_server/server_socket.h
Fixes an issue with port forwarding when localhost on the remote system maps to the IPV6 localhost. In that case the server would time out on accept() since it creates an IPV4 socket, so the connection is never established.
Also allows passing in port 0, so that it will auto-detect an available port. This will be used in a future CL to remove the necessity of running netstat/ss.
=> [cdc_rsync] Fix issue with IPV6 localhosts

.github/workflows/create_release.yml, .github/workflows/lint.yml, cdc_rsync/cdc_rsync_client.cc, cdc_rsync/cdc_rsync_client.h, cdc_rsync/client_socket.cc, cdc_rsync_server/cdc_rsync_server.cc, cdc_rsync_server/cdc_rsync_server.h, cdc_rsync_server/main.cc, common/port_manager_test.cc, common/port_manager_win.cc
Instead of calling netstat on the remote device to detect available ports, simply call bind with port 0 to bind to any available port. Since the port is not yet known when cdc_rsync_server.exe is called, port forwarding needs to be started AFTER the server reports its port.
=> [cdc_rsync] Use any available server port

cdc_rsync/cdc_rsync_client.cc, common/BUILD, common/client_socket.cc, common/client_socket.h, common/server_socket.cc, common/socket_internal.h
Uses the abstractions written for ServerSocket in ClientSocket, so that it builds on Linux. Also adds a method to poll for connections and uses that in cdc_rsync. Similar code will be used in cdc_fuse_fs to wait for a connection in a future CL.
=> [common] Add support for ClientSocket on Linux
